### ISSUE TITLE
company-irony breaks irony-snippet-expand

### ISSUE THREAD

**Issue by zakkak** [Sarcasm/company-irony#16]
When using irony without company-irony I get completion as expected and snippets work fine.  On the other hand when using company-irony snippets are not working.

Any ideas?

**Comment by zakkak** [comment]
Well, reading  #13 (should have read it earlier), I understand that I need the yas-minor-mode enabled for it to work.  However, how comes and it works fine with the vanilla irony completion even with yas-mode disabled?

**Comment by Sarcasm** [comment]
> However, how comes and it works fine with the vanilla irony completion even with yas-mode disabled?

Hum, that's disturbing. Vanilla completion is completion-at-point?
What does the snippet looks like? The vanilla completion does not use snippets at all, so I don't see how it could work. A screenshot would be appreciated.

**Comment by zakkak** [comment]
Sorry, for being unclear.  By vanilla completion I mean the completion provided by irony-mode without using the company-irony package (but still using company, if that matters).

**Comment by Sarcasm** [comment]
Hum, what company backend is displayed in the mode line? `company-clang` or `company-capf` or something else?

**Comment by zakkak** [comment]
The enabled minor modes are:

```
Enabled minor modes: Abbrev Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Column-Number Company Company-Statistics
Delete-Selection Eldoc Electric-Indent File-Name-Shadow Flx-Ido
Flycheck Flyspell Font-Lock Global-Auto-Revert Global-Company
Global-Font-Lock Global-Undo-Tree Global-Whitespace Guide-Key
Ido-Everywhere Ido-Ubiquitous Ido-Vertical Irony Irony-Eldoc
Line-Number Mouse-Wheel Override-Global Pdf-Occur-Global
Rainbow-Delimiters Show-Smartparens Show-Smartparens-Global Smart-Tabs
Smartparens Smartparens-Global Tex-Pdf Tex-Source-Correlate
Transient-Mark Undo-Tree Whole-Line-Or-Region Xclip Xterm-Mouse Yas
```

And the company-backends are:

```
company-backends is a variable defined in `company.el'.
Its value is (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
	      (company-dabbrev-code company-gtags company-etags company-keywords)
	      company-oddmuse company-files company-dabbrev)
```

So i guess it is company-clang that gets in the way.

**Comment by Sarcasm** [comment]
I guess so, you can see it in the mode-line, when completion is active "company" will be renamed to "company-xxx", where xxx is the backend in use.

Anyway, here the conclusion is that, in one case you get something like company-clang with company snippets, and in the other case you use company-irony, which uses yasnippet-only for now, which needs to be enabled. A nice thing would be to support company templates as a snippet mechanism in addition to yasnippet, I never got to do it.

**Comment by zakkak** [comment]
> I guess so, you can see it in the mode-line, when completion is active "company" will be renamed to company-xxx", where xxx is the backend in use.

No, that's not the case I just see company in the mode-line no matter the backend (maybe it's my mode-line configuration).

> Anyway, here the conclusion is that, in one case you get something like company-clang with company snippets, and in the other case you use company-irony, which uses yasnippet-only for now, which needs to be enabled. A nice thing would be to support company templates as a snippet mechanism in addition to yasnippet, I never got to do it.

Unfortunately I am not familiar with company mode and its mechanisms so I cannot help here.

Thanks for tracing this :)
