### ISSUE TITLE
company-irony vs vanilla irony completion

### ISSUE THREAD

**Issue by zakkak** [Sarcasm/company-irony#17]
What are the differences between the two completion methods?  Could you please provide a comparison on the readme file?

Is company-irony just an interface to company-mode or does it offer more features than the vanilla completion?

Thanks for your great work :) Keep it up!

**Comment by Sarcasm** [comment]
> What are the differences between the two completion methods? Could you please provide a comparison on the readme file?

The differences are the same as with company and completion-at-point, I think it's just company that should document its functionality.

Anyway I could probably add a few lines, like "Asynchronous completion".

> Is company-irony just an interface to company-mode or does it offer more features than the vanilla completion?

irony is just an interface to company, so it offers the same advantage over vanilla completion than company mode in general.

I will think about adding a few lines.
