### ISSUE TITLE
company-irony will break company-yasnippet.

### ISSUE THREAD

**Issue by nopcall** [Sarcasm/company-irony#19]
After add company-irony to company-backends, company-yasnippet not work.
For example, 
for|   will show yasnippet's candidates 
but after added company-irony to company-backends,
for| only show "forward_iterator_tag".

buffer variable: company-backends
Value: ((company-irony-c-headers company-irony)
 company-gtags company-yasnippet
 (company-capf :with company-dabbrev-code company-files))

**Comment by Sarcasm** [comment]
if you want company-yasnippet you have to add it to the group of company-irony:

    (company-irony-c-headers company-irony) ...

should become:
    (company-irony-c-headers company-irony company-yasnippet) ...

**Comment by nopcall** [comment]
Thanks, it works now.
