### ISSUE TITLE
Invalid function: irony--without-narrow

### ISSUE THREAD

**Issue by chester755** [Sarcasm/company-irony#20]
Hi,

I am a bit confused at moment, I realise that it's probably not a company-irony issue. But the error message appeared when I trying to use company mode to auto complete anything c/c++ related.

This happened when I installed the latest version of Irony mode (20160123) on my emacs 24.5.

I have my old Irony mode (20141030) installed previously, which works for me. As I needed more function, I decide to install a newer version of it.

If I replace my new version with old version, the old one still works.

I am still relatively new to emacs. If there is any information you need for helping me debug this. Please let me know how to get them. 

Thanks

**Comment by Sarcasm** [comment]
remove the packages, reinstall the latest ones, restart emacs. If this does not work we can take more time to investigate but I think that should be sufficient to get rid of the already loaded libraries or things like that.

**Comment by chester755** [comment]
Thanks for your help, and sorry for this late reply I was very busy with my work for the past 3 days. Your word "reinstall" inspired me actually. I usually just remove the package from the elpa directory, which doesn't work properly with irony mode. I removed the package using package menu and reinstalled it. After applying irony-install-server again, it worked. Thanks a lot! I will not close the issue.
