### ISSUE TITLE
No way to cancel inserting function arguments

### ISSUE THREAD

**Issue by tttuuu888** [Sarcasm/company-irony#23]
Hello.
I daily use company-irony and really appreciate for your work.

Recently I have been looking for a way to cancel inserting function arguments in the middle but I couldn't find it.
As far as I remember, canceling was available until some months ago. If I cancel with C-g in the middle of  arguments, guide strings were disappeared. But now guide strings are remained.
Therefore I should delete remained strings by myself.

The example case is as below.

printf("Test\n"<Cursor>, ...)

When printf is completed with company-irony and cursor is located at <Cursor> position, there is no way to cancel ,... part. 
The option to cancel it would be great.

Thanks.

**Comment by tttuuu888** [comment]
[](url)

**Comment by Sarcasm** [comment]
Maybe a few months ago you were using yasnippet? If yasnippet is enabled, it will be used. If it is not, we now fall back to company-mode own snippet mechanism.

**Comment by tttuuu888** [comment]
I missed the point. I thought it was from company-irony but actually was from company-mode.  I may ask about this to author of company-mode. Thanks.
