### ISSUE TITLE
backend can't access company functions?

### ISSUE THREAD

**Issue by LouLinear** [Sarcasm/company-irony#25]
My company-irony--post-completion seems unable to access the following company function:
Debugger entered--Lisp error: (void-function company-template-c-like-templatify)

When programming in c++. The function company-template-c-like-templatify is in company-clang.el

**Comment by Sarcasm** [comment]
> The function company-template-c-like-templatify is in company-clang.el

It looks like it's in `company-template`, https://github.com/company-mode/company-mode/blob/c353c7137f5c79790124990a2f7b7268afea785a/company-template.el#L147

How do you notice the issue?

I will add an explicit require for this.

**Comment by Sarcasm** [comment]
Closed by https://github.com/Sarcasm/company-irony/commit/f1d6761c581fd12fa1188e26478c0229d8348332
