### ISSUE TITLE
No completion for function args if result is 'common' with other candidates

### ISSUE THREAD

**Issue by mattbreeden** [Sarcasm/company-irony#41]
Was hoping you could help direct me where to look to solve this issue- not even sure it has anything to do with this package.

When completing functions I usually get the nice function arguments. However if the function I complete shares its' identifier (pre-'(') with other candidates, I no longer get those completions. As an example:
```
pow|
  pow(double __x, double __y)
  powf(float __x, float __y)
  powl(long double __x, long double __y)
```
In this scenario my cursor is '|'. If I autocomplete here I am left with just the word `pow`, but if I autocomplete either of the other two results I would get their full completion `powf(float __x, float __y)`.

**Comment by Sarcasm** [comment]
I cannot reproduce the issue. With the company default binding, I select the first item in the list, hit enter, and everything is inserted.

Do you hit enter to complete the candidate or do you have some smart tab configuration or something like that?

**Comment by mattbreeden** [comment]
> Do you hit enter to complete the candidate or do you have some smart tab configuration or something like that?

Either. Tried all of the company-complete type functions. Don't want to bother you with this if it's not your issue. Just wasn't sure where to start looking.
