### ISSUE TITLE
Error in auto completion with backend company-irony

### ISSUE THREAD

**Issue by lrleon** [Sarcasm/company-irony#48]
I updated some Emacs packages about a week ago, and since then, irony has broken. As soon I start to type anything, emacs prints out the following message: `backend company-irony error `Symbol's function definition is void: pos-bol" with args (prefix)`

No idea about what could be causing the problem. Any help, please?

**Comment by Sarcasm** [comment]
Thanks for the report!
In the latest release I did not realized that I started using an Emacs 29 feature.
The latest irony-mode release 1.6.1 should fix the issue, if you can confirm that would be great.

**Comment by lrleon** [comment]
Farpait! Thanks a lot!
